import { FormEvent, PointerEvent as ReactPointerEvent, useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import "./App.css";

type Page = string;
type ReportPeriod = "daily" | "weekly" | "monthly" | "quarterly" | "yearly" | "custom";
type MenuAction = "visibility" | "period" | "rename" | "icon" | "delete";
type NavigationMenu = { id: string; label: string; iconSvg: string; sortOrder: number; isSystem: boolean; isHidden: boolean; reportPeriod: ReportPeriod };
type Preferences = { sidebarCollapsed: boolean; defaultPageId: string; weekStart: string; exportDirectory: string; minimizeToTray: boolean; menuActionOrder: MenuAction[]; menus: NavigationMenu[] };
type Dialog = "manage" | "add" | "rename" | "icon" | "period" | "delete" | "sort" | null;
const NS = "http://www.w3.org/2000/svg";
const icon = (paths: string) => `<svg xmlns="${NS}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths}</svg>`;
const icons = {
  home: icon('<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1Z"/><path d="M9 21v-6h6v6"/>'), daily: icon('<path d="M6 3h9l3 3v15H6z"/><path d="M9 12h6M9 16h6M9 8h3"/>'), folder: icon('<path d="M3 7h7l2 2h9v11H3z"/>'), list: icon('<path d="M9 6h11M9 12h11M9 18h11"/><path d="m3 6 1 1 2-2m-3 7 1 1 2-2m-3 7 1 1 2-2"/>'), settings: icon('<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.1 2.1-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.55V20.3h-3v-.1A1.7 1.7 0 0 0 10.7 18.65a1.7 1.7 0 0 0-1.88.34l-.06.06-2.1-2.1.06-.06A1.7 1.7 0 0 0 7.06 15 1.7 1.7 0 0 0 5.5 14H5.4v-3h.1a1.7 1.7 0 0 0 1.56-1.03 1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.1-2.1.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 11.7 4.8v-.1h3v.1a1.7 1.7 0 0 0 1.03 1.55 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.1 2.1-.06.06a1.7 1.7 0 0 0-.34 1.88A1.7 1.7 0 0 0 20.9 11h.1v3h-.1A1.7 1.7 0 0 0 19.4 15Z"/>'),
  menu: icon('<path d="M4 6h16M4 12h16M4 18h16"/>'), search: icon('<circle cx="11" cy="11" r="6"/><path d="m20 20-4-4"/>'), rename: icon('<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/>'), change: icon('<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/>'), calendar: icon('<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M8 2v4M16 2v4M3 10h18M8 14h3M8 17h7"/>'), eye: icon('<path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>'), hidden: icon('<path d="m3 3 18 18"/><path d="M10.6 6.2A11.6 11.6 0 0 1 12 6c6.5 0 10 6 10 6a18 18 0 0 1-3 3.7M6.2 6.2C3.6 8 2 12 2 12s3.5 6 10 6a10 10 0 0 0 3.8-.7"/><path d="M9.9 9.9a3 3 0 0 0 4.2 4.2"/>'), trash: icon('<path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v5M14 11v5"/>')
};
const iconChoices = [{ name: "首页", svg: icons.home }, { name: "日报", svg: icons.daily }, { name: "文件夹", svg: icons.folder }, { name: "清单", svg: icons.list }, { name: "设置", svg: icons.settings }];
const periods: { value: ReportPeriod; label: string }[] = [{ value: "daily", label: "每日" }, { value: "weekly", label: "每周" }, { value: "monthly", label: "每月" }, { value: "quarterly", label: "每季度" }, { value: "yearly", label: "每年" }, { value: "custom", label: "自定义" }];
const periodName = (value: ReportPeriod) => periods.find((period) => period.value === value)?.label ?? "每日";
const today = new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "long", day: "numeric", weekday: "long" }).format(new Date());

function SvgIcon({ svg }: { svg: string }) { const complete = /<svg\b[^>]*\bxmlns=/.test(svg) ? svg : svg.replace(/<svg\b/, `<svg xmlns="${NS}"`); const raw = new TextEncoder().encode(complete); let binary = ""; for (const byte of raw) binary += String.fromCharCode(byte); const image = `url("data:image/svg+xml;base64,${btoa(binary)}")`; return <span className="svg-icon" aria-hidden="true" style={{ WebkitMaskImage: image, maskImage: image }} />; }
function DialogShell({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="dialog-backdrop" onMouseDown={onClose}><section className="dialog" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><div className="dialog-heading"><h2>{title}</h2><button className="dialog-close" onClick={onClose} aria-label="关闭对话框">×</button></div>{children}</section></div>; }
const actionLabels: Record<MenuAction, string> = { visibility: "隐藏菜单", period: "报告周期", rename: "重命名菜单", icon: "修改菜单图标", delete: "删除菜单" };

/** Horizontally reorders the controls used at the right of every menu row. */
function SortMenuActions({ actions, onSorted }: { actions: MenuAction[]; onSorted: (actions: MenuAction[]) => void }) {
  const [dragged, setDragged] = useState<MenuAction | null>(null); const [target, setTarget] = useState<MenuAction | null>(null); const active = useRef<MenuAction | null>(null); const drop = useRef<MenuAction | null>(null);
  const reset = () => { active.current = null; drop.current = null; setDragged(null); setTarget(null); };
  const update = (event: ReactPointerEvent<HTMLButtonElement>) => { const item = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-action-id]")?.dataset.actionId as MenuAction | undefined; if (!item || item === active.current) { drop.current = null; setTarget(null); return; } drop.current = item; setTarget(item); };
  const finish = () => { const source = active.current; const destination = drop.current; reset(); if (!source || !destination || source === destination) return; const next = actions.filter((action) => action !== source); next.splice(next.indexOf(destination), 0, source); onSorted(next); };
  return <div className="action-sort-list" onPointerLeave={() => { drop.current = null; setTarget(null); }}>{actions.map((action) => <button key={action} data-action-id={action} className={`action-sort-item ${dragged === action ? "is-dragging" : ""} ${target === action ? "is-drop-target" : ""}`} onPointerDown={(event) => { if (!event.isPrimary || event.button !== 0) return; event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); active.current = action; setDragged(action); }} onPointerMove={update} onPointerUp={finish} onPointerCancel={reset}><span className="drag-handle" aria-hidden="true">⠿</span>{actionLabels[action]}</button>)}</div>;
}

function MenuActions({ item, order, onToggleHidden, onEdit, onDelete }: { item: NavigationMenu; order: MenuAction[]; onToggleHidden: (item: NavigationMenu) => void; onEdit: (item: NavigationMenu, type: "rename" | "icon" | "period") => void; onDelete: (item: NavigationMenu) => void }) {
  return <div className="menu-actions">{order.map((action) => {
    if (action === "visibility") return !item.isSystem && <button key={action} className={`icon-button ${item.isHidden ? "is-active" : ""}`} title={item.isHidden ? "显示菜单" : "隐藏菜单"} aria-label={item.isHidden ? "显示菜单" : "隐藏菜单"} aria-pressed={item.isHidden} onClick={() => onToggleHidden(item)}><SvgIcon svg={item.isHidden ? icons.hidden : icons.eye} /></button>;
    if (action === "period") return !item.isSystem && <button key={action} className="icon-button" title="报告周期" aria-label="报告周期" onClick={() => onEdit(item, "period")}><SvgIcon svg={icons.calendar} /></button>;
    if (action === "rename") return <button key={action} className="icon-button" title="重命名菜单" aria-label="重命名菜单" onClick={() => onEdit(item, "rename")}><SvgIcon svg={icons.rename} /></button>;
    if (action === "icon") return <button key={action} className="icon-button" title="修改菜单图标" aria-label="修改菜单图标" onClick={() => onEdit(item, "icon")}><SvgIcon svg={icons.change} /></button>;
    return !item.isSystem && <button key={action} className="icon-button danger-icon" title="删除菜单" aria-label="删除菜单" onClick={() => onDelete(item)}><SvgIcon svg={icons.trash} /></button>;
  })}</div>;
}

export default function App() {
  const [preferences, setPreferences] = useState<Preferences | null>(null); const [page, setPage] = useState<Page>("home"); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(`${today.replace(/星期.*/, "")}日报`); const [content, setContent] = useState(""); const [notice, setNotice] = useState(""); const [toasts, setToasts] = useState<{ id: number; message: string }[]>([]);
  const toast = (message: string) => { const id = Date.now() + Math.random(); setToasts((current) => [...current, { id, message }]); window.setTimeout(() => setToasts((current) => current.filter((item) => item.id !== id)), 3200); };
  useEffect(() => { void invoke("show_main_window"); void invoke<Preferences>("get_app_preferences").then((saved) => { setPreferences(saved); const visible = saved.menus.filter((item) => !item.isHidden); setPage(visible.some((item) => item.id === saved.defaultPageId) ? saved.defaultPageId : visible[0]?.id ?? "home"); }).catch((error) => console.error("无法读取偏好设置", error)); }, []);
  const persist = (next: Preferences, message = "已保存设置") => { setPreferences(next); void invoke<Preferences>("save_app_preferences", { preferences: next }).then((saved) => { setPreferences(saved); toast(message); }).catch((error) => { console.error("无法保存偏好设置", error); toast("设置保存失败，请稍后重试。"); }); };
  const applySaved = (next: Preferences, message = "已保存设置") => { setPreferences(next); toast(message); };
  if (!preferences) return <div className="app-loading">正在载入本地设置…</div>;
  const visible = preferences.menus.filter((item) => !item.isHidden); const activeMenu = preferences.menus.find((item) => item.id === page); const label = activeMenu?.label ?? "首页"; const createDaily = () => { setPage("daily"); setEditing(true); setNotice(""); };
  return <div className={`app-shell ${preferences.sidebarCollapsed ? "sidebar-collapsed" : ""}`}><aside className="sidebar"><div className="sidebar-toolbar"><span className="brand-name">ReportManager</span><div className="toolbar-actions"><button className="toolbar-icon" title={preferences.sidebarCollapsed ? "展开侧边栏" : "收起侧边栏"} onClick={() => persist({ ...preferences, sidebarCollapsed: !preferences.sidebarCollapsed })}><SvgIcon svg={icons.menu} /></button><button className="toolbar-icon search-button" title="搜索（即将推出）" onClick={() => toast("搜索功能即将推出")}><SvgIcon svg={icons.search} /></button></div></div><nav aria-label="主导航">{visible.map((item) => <button key={item.id} title={preferences.sidebarCollapsed ? item.label : undefined} className={`nav-item ${page === item.id ? "active" : ""}`} onClick={() => { setPage(item.id); setEditing(false); }}><SvgIcon svg={item.iconSvg} /><span className="nav-label">{item.label}</span></button>)}</nav><div className="sidebar-bottom"><span className="offline-dot" /><span className="offline-text">所有内容仅保存在本机</span></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">{label}</p><h1>{page === "home" ? "工作记录，一目了然" : label}</h1></div><button className="primary" onClick={createDaily}>＋ 新建今日日报</button></header>{page === "home" && <Home onCreate={createDaily} />}{page === "daily" && (editing ? <DailyEditor title={title} content={content} notice={notice} onTitle={setTitle} onContent={setContent} /> : <RecordList type={label} onCreate={createDaily} />)}{(page === "weekly" || page === "meeting" || (!activeMenu?.isSystem && page !== "home")) && <RecordList type={label} onCreate={() => setEditing(true)} />}{page === "settings" && <Settings preferences={preferences} persist={persist} applySaved={applySaved} setPage={setPage} />}</main><div className="toast-stack" aria-live="polite">{toasts.map((item) => <button key={item.id} className="toast" onClick={() => setToasts((current) => current.filter((toastItem) => toastItem.id !== item.id))}>{item.message}</button>)}</div></div>;
}
function Home({ onCreate }: { onCreate: () => void }) { return <div className="page-stack"><section className="welcome-card"><div><p className="muted">今天是 {today}</p><h2>从一份清晰的日报开始</h2><p>记录进展、风险与下一步计划，让工作脉络随时可追溯。</p><button className="primary" onClick={onCreate}>创建今日日报</button></div><span className="calendar">20</span></section><section className="status-grid">{[["今日日报", "尚未创建", "立即创建"], ["本周周报", "等待整理", "查看周报"], ["今日例会", "尚未记录", "开始记录"]].map(([itemLabel, value, action]) => <article className="status-card" key={itemLabel}><p>{itemLabel}</p><h3>{value}</h3><button className="text-button">{action} →</button></article>)}</section><section className="panel"><div className="section-heading"><div><h2>最近编辑</h2><p>你最近更新的工作记录会显示在这里。</p></div><button className="text-button">查看全部记录 →</button></div><div className="empty-state"><span>▤</span><h3>还没有工作记录</h3><p>创建第一份日报，开始沉淀你的工作成果。</p></div></section></div>; }
function RecordList({ type, onCreate }: { type: string; onCreate: () => void }) { return <div className="page-stack"><section className="toolbar panel"><input aria-label="搜索记录" placeholder={`搜索${type}标题、正文或标签`} /><button className="secondary">筛选日期</button><button className="secondary">标签</button><button className="primary" onClick={onCreate}>新建{type}</button></section><section className="panel empty-state"><span>⌕</span><h3>暂无{type}</h3><p>创建后可以按日期、标签和关键词快速检索。</p></section></div>; }
function DailyEditor({ title, content, notice, onTitle, onContent }: { title: string; content: string; notice: string; onTitle: (value: string) => void; onContent: (value: string) => void }) { const [savedNotice, setSavedNotice] = useState(notice); const save = (event: FormEvent) => { event.preventDefault(); setSavedNotice("草稿已保存。连接本地数据库后将自动持久化到 SQLite。"); }; return <form className="editor page-stack" onSubmit={save}><section className="editor-header"><div><input className="title-input" value={title} onChange={(event) => onTitle(event.target.value)} aria-label="日报标题" /><p className="muted">记录日期：{today}</p></div><div className="editor-actions"><button type="button" className="secondary">复制纯文本</button><button type="button" className="secondary">导出 Markdown</button><button className="primary">保存草稿</button></div></section>{savedNotice && <p className="notice" role="status">{savedNotice}</p>}<section className="editor-grid"><div className="panel writing"><label htmlFor="daily-content">正文</label><textarea id="daily-content" value={content} onChange={(event) => onContent(event.target.value)} placeholder={"1. 今日完成：\n2. 进行中：\n3. 问题与风险：\n4. 下一步计划："} /></div><aside className="panel structured-fields"><h2>结构化信息（可选）</h2>{["完成事项", "进行中事项", "问题与风险", "下一步计划", "标签"].map((field) => <label key={field}>{field}<input placeholder={`填写${field}`} /></label>)}</aside></section></form>; }

function Settings({ preferences, persist, applySaved, setPage }: { preferences: Preferences; persist: (next: Preferences, message?: string) => void; applySaved: (next: Preferences, message?: string) => void; setPage: (page: Page) => void }) {
  const [dialog, setDialog] = useState<Dialog>(null); const [selected, setSelected] = useState<NavigationMenu | null>(null); const [label, setLabel] = useState(""); const [svg, setSvg] = useState(icons.daily); const [period, setPeriod] = useState<ReportPeriod>("daily");
  const edit = (menu: NavigationMenu, type: "rename" | "icon" | "period") => { setSelected(menu); setLabel(menu.label); setSvg(menu.iconSvg); setPeriod(menu.reportPeriod); setDialog(type); };
  const save = (changes: Partial<NavigationMenu>, message: string) => { if (!selected) return; persist({ ...preferences, menus: preferences.menus.map((menu) => menu.id === selected.id ? { ...menu, ...changes } : menu) }, message); setDialog("manage"); };
  // Home and Settings are always reachable, even if an outdated client sends
  // a stale hidden flag back to the backend.
  const toggleHidden = (item: NavigationMenu) => { if (item.id === "home" || item.id === "settings") return; persist({ ...preferences, menus: preferences.menus.map((menu) => menu.id === item.id ? { ...menu, isHidden: !menu.isHidden } : menu) }, item.isHidden ? "菜单已显示" : "菜单已隐藏"); };
  const add = () => { const name = label.trim(); if (!name) return; const menu: NavigationMenu = { id: `custom-${crypto.randomUUID()}`, label: name, iconSvg: svg, sortOrder: preferences.menus.length - 1, isSystem: false, isHidden: false, reportPeriod: "daily" }; void invoke<Preferences>("create_navigation_menu", { menu }).then((next) => { applySaved(next, "菜单已添加"); setDialog("manage"); }).catch((error) => window.alert(String(error))); };
  const remove = () => { if (!selected) return; void invoke<Preferences>("delete_navigation_menu", { id: selected.id }).then((next) => { if (preferences.defaultPageId === selected.id) persist({ ...next, defaultPageId: "home" }, "菜单已删除"); else applySaved(next, "菜单已删除"); setPage("settings"); setDialog("manage"); }).catch((error) => window.alert(String(error))); };
  const visible = preferences.menus.filter((item) => !item.isHidden);
  return <div className="page-stack settings-page"><section className="panel settings"><h2>偏好设置</h2><label>启动后默认进入页面<select value={visible.some((item) => item.id === preferences.defaultPageId) ? preferences.defaultPageId : ""} onChange={(event) => persist({ ...preferences, defaultPageId: event.target.value })}><option value="" disabled>请选择可见菜单</option>{visible.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>界面语言<select defaultValue="zh-CN"><option value="zh-CN">简体中文</option></select></label><label>每周起始日<select value={preferences.weekStart} onChange={(event) => persist({ ...preferences, weekStart: event.target.value })}><option value="monday">周一</option><option value="sunday">周日</option></select></label><label>默认导出目录<input value={preferences.exportDirectory} placeholder="尚未设置，导出时选择" onChange={(event) => persist({ ...preferences, exportDirectory: event.target.value })} /></label></section><section className="panel menu-settings"><div className="section-heading"><div><h2>菜单管理</h2><p>管理菜单显示、报告周期、名称和图标；首页始终置顶，设置始终置底。</p></div><button className="secondary" onClick={() => setDialog("manage")}>菜单管理</button></div></section><section className="panel settings-other"><h2>其他</h2><label className="checkbox-setting"><input type="checkbox" checked={preferences.minimizeToTray} onChange={(event) => persist({ ...preferences, minimizeToTray: event.target.checked }, "关闭窗口行为已更新")} /><span><strong>关闭窗口时最小化到系统托盘</strong><small>开启后，点击关闭按钮会隐藏主窗口；关闭后会直接退出程序。</small></span></label></section><section className="panel setting-row"><div><h3>本地数据备份</h3><p>导出全部数据以便备份或迁移。内容不会上传到网络。</p></div><button className="secondary">导出全部数据</button></section>
    {dialog === "manage" && <DialogShell title="菜单管理" onClose={() => setDialog(null)}><p className="dialog-description">可管理报告菜单的显示、周期、名称和图标；首页和设置始终保持可见。</p><div className="menu-list">{preferences.menus.map((item) => <div className="menu-row menu-management-row" key={item.id}><span className="menu-row-spacer" /><SvgIcon svg={item.iconSvg} /><span className="menu-row-label">{item.label}{!item.isSystem && <small className="menu-period">● {periodName(item.reportPeriod)}</small>}</span><MenuActions item={item} order={preferences.menuActionOrder} onToggleHidden={toggleHidden} onEdit={edit} onDelete={(menu) => { setSelected(menu); setDialog("delete"); }} /></div>)}</div><div className="manage-dialog-actions"><button className="secondary" onClick={() => setDialog("sort")}>修改按钮功能顺序</button><button className="secondary" onClick={() => { setLabel(""); setSvg(icons.daily); setDialog("add"); }}>＋ 添加菜单</button></div></DialogShell>}
    {dialog === "sort" && <DialogShell title="修改按钮功能顺序" onClose={() => setDialog("manage")}><p className="dialog-description">水平拖拽按钮调整每行右侧功能按钮的显示顺序，松开后会立即保存并应用到所有菜单。</p><SortMenuActions actions={preferences.menuActionOrder} onSorted={(menuActionOrder) => persist({ ...preferences, menuActionOrder }, "按钮功能顺序已更新")} /><div className="dialog-actions"><button className="secondary" onClick={() => setDialog("manage")}>完成</button></div></DialogShell>}
    {dialog === "add" && <DialogShell title="添加菜单" onClose={() => setDialog("manage")}><p className="dialog-description">新菜单会添加在“设置”菜单之前，默认报告周期为每日。</p><label className="dialog-field">菜单名称<input value={label} onChange={(event) => setLabel(event.target.value)} autoFocus /></label><label className="dialog-field">菜单图标<select value={svg} onChange={(event) => setSvg(event.target.value)}>{iconChoices.map((item) => <option key={item.name} value={item.svg}>{item.name}</option>)}</select></label><div className="dialog-actions"><button className="secondary" onClick={() => setDialog("manage")}>取消</button><button className="primary" disabled={!label.trim()} onClick={add}>添加菜单</button></div></DialogShell>}
    {dialog === "rename" && selected && <DialogShell title="重命名菜单" onClose={() => setDialog("manage")}><label className="dialog-field">新名称<input value={label} onChange={(event) => setLabel(event.target.value)} autoFocus /></label><div className="dialog-actions"><button className="secondary" onClick={() => setDialog("manage")}>取消</button><button className="primary" disabled={!label.trim()} onClick={() => save({ label: label.trim() }, "菜单名称已更新")}>保存</button></div></DialogShell>}
    {dialog === "icon" && selected && <DialogShell title="修改菜单图标" onClose={() => setDialog("manage")}><label className="dialog-field">菜单图标<select value={svg} onChange={(event) => setSvg(event.target.value)} autoFocus>{iconChoices.map((item) => <option key={item.name} value={item.svg}>{item.name}</option>)}</select></label><div className="dialog-actions"><button className="secondary" onClick={() => setDialog("manage")}>取消</button><button className="primary" onClick={() => save({ iconSvg: svg }, "菜单图标已更新")}>保存</button></div></DialogShell>}
    {dialog === "period" && selected && <DialogShell title="报告周期" onClose={() => setDialog("manage")}><label className="dialog-field">报告周期<select value={period} onChange={(event) => setPeriod(event.target.value as ReportPeriod)} autoFocus>{periods.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><div className="dialog-actions"><button className="secondary" onClick={() => setDialog("manage")}>取消</button><button className="primary" onClick={() => save({ reportPeriod: period }, "报告周期已更新")}>保存</button></div></DialogShell>}
    {dialog === "delete" && selected && <DialogShell title="删除菜单" onClose={() => setDialog("manage")}><p className="dialog-description">确定删除“{selected.label}”吗？仅可删除没有关联报告的自定义菜单，删除后不可恢复。</p><div className="dialog-actions"><button className="secondary" onClick={() => setDialog("manage")}>取消</button><button className="danger-button" onClick={remove}>确认删除</button></div></DialogShell>}</div>;
}
